---
abstract: 'calculate birthdate and week numbers for a pregnancy'
author:
  - 'Jonas B. Nielsen, (jonasbn) - C<< <jonasbn@cpan.org> >>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-Pregnancy
provides:
  Date::Pregnancy:
    file: lib/Date/Pregnancy.pm
    version: '0.04'
requires:
  Carp: '0'
  Clone: '0'
  DateTime: '0'
  Exporter: '0'
  File::Find: '0'
  File::Spec: '0'
  POSIX: '0'
  Test::More: '0'
  perl: '5.008'
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
